CREATE TABLE IF NOT EXISTS `wh_mdt_reports` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `author` VARCHAR(80) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `body` LONGTEXT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `wh_mdt_incidents` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `author` VARCHAR(80) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `body` LONGTEXT NOT NULL,
  `officers` JSON NULL,
  `suspects` JSON NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `wh_mdt_bulletins` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `author` VARCHAR(80) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `body` LONGTEXT NOT NULL,
  `priority` VARCHAR(32) DEFAULT 'normal',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `wh_mdt_dovs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `author` VARCHAR(80) NOT NULL,
  `plate` VARCHAR(32) NOT NULL,
  `note` LONGTEXT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `wh_mdt_registrations` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `owner_cid` VARCHAR(80) NOT NULL,
  `plate` VARCHAR(32) NOT NULL,
  `category` VARCHAR(32) NOT NULL,
  `fee` INT NOT NULL,
  `registered_by` VARCHAR(80) NOT NULL,
  `issued_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `expires_at` TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS `wh_mdt_license_actions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `author` VARCHAR(80) NOT NULL,
  `subject_name` VARCHAR(120) NOT NULL,
  `subject_cid` VARCHAR(80) NULL,
  `license_type` VARCHAR(32) NOT NULL,
  `action` VARCHAR(32) NOT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `notes` LONGTEXT NULL,
  `expires_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
